//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMyBlogEntities : DbContext
    {
        public DbMyBlogEntities()
            : base("name=DbMyBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_comment> tbl_comment { get; set; }
        public virtual DbSet<tbl_post> tbl_post { get; set; }
        public virtual DbSet<tbl_tag> tbl_tag { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
